/*
 Proyecto morral.
 Integrantes:
 Maria Alejandra Pabon Salazar 1310263
 Mayerly Suarez Ordoñez        1310284
 */

/*
 *Proposito: 
 */
package morral;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lpsolve.LpSolveException;
//import org.jfree.chart.ChartFactory;
//import org.jfree.chart.ChartPanel;
//import org.jfree.chart.JFreeChart;
//import org.jfree.chart.plot.PlotOrientation;
//import org.jfree.data.category.DefaultCategoryDataset;
//import org.jfree.data.xy.IntervalXYDataset;

public class Morral extends javax.swing.JFrame {

    /*Variables globales*/
    int numeroCajas = 0;
    double[] pesosCajas = null;
    double[] volumenesCajas = null;
    int[] numerosCaja = null;
    double pesoMorral = 0;
    double volumenMorral = 0;
    int[] morrales = null;
    String[] cajasEnMorrales = null;
    DefaultTableModel modelMorral;
    DefaultTableModel modelCaja;
    DefaultTableModel modelResultado;

    /*Constructor*/
    @SuppressWarnings("empty-statement")
    public Morral() {

        initComponents();
        this.setTitle("Optimizacion Morrales");
        modelMorral = (DefaultTableModel) tablaMorral.getModel();
        modelCaja = (DefaultTableModel) tablaCaja.getModel();
        modelResultado = (DefaultTableModel) tablaResultado.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rutArchivo = new javax.swing.JTextField();
        examinarArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCaja = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMorral = new javax.swing.JTable();
        Calcular = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaResultado = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        funcionobjetivolabel = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        resultiempoejecucion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tiempoejecucionlabel1 = new javax.swing.JLabel();
        funcionobjetivolabel1 = new javax.swing.JLabel();
        limpiarTabla = new javax.swing.JButton();
        funcionobjetivolabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulacion ascensor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Problema Morrales");

        rutArchivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        examinarArchivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        examinarArchivo.setText("Examinar");
        examinarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examinarArchivoActionPerformed(evt);
            }
        });

        tablaCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Peso", "Volumen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCaja.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaCaja);
        if (tablaCaja.getColumnModel().getColumnCount() > 0) {
            tablaCaja.getColumnModel().getColumn(0).setResizable(false);
            tablaCaja.getColumnModel().getColumn(1).setResizable(false);
            tablaCaja.getColumnModel().getColumn(2).setResizable(false);
        }

        tablaMorral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Cajas", "Peso", "Volumen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMorral.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaMorral);
        if (tablaMorral.getColumnModel().getColumnCount() > 0) {
            tablaMorral.getColumnModel().getColumn(0).setResizable(false);
            tablaMorral.getColumnModel().getColumn(1).setResizable(false);
            tablaMorral.getColumnModel().getColumn(2).setResizable(false);
        }

        Calcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        tablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Morral", "Cajas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaResultado.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaResultado);
        if (tablaResultado.getColumnModel().getColumnCount() > 0) {
            tablaResultado.getColumnModel().getColumn(0).setResizable(false);
            tablaResultado.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Graficar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        funcionobjetivolabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        funcionobjetivolabel.setForeground(new java.awt.Color(102, 102, 102));
        funcionobjetivolabel.setText("Total minimo de personas");

        resultado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Datos Cajas");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Datos Morral");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/morral/morral2.png"))); // NOI18N

        resultiempoejecucion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Distribución de las cajas en los morrales");

        tiempoejecucionlabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tiempoejecucionlabel1.setForeground(new java.awt.Color(102, 102, 102));
        tiempoejecucionlabel1.setText("Tiempo de ejecucion");

        funcionobjetivolabel1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        funcionobjetivolabel1.setForeground(new java.awt.Color(102, 102, 102));
        funcionobjetivolabel1.setText("(Total minimo de morrales)");

        limpiarTabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        limpiarTabla.setText("Limpiar datos");
        limpiarTabla.setToolTipText("Limpiar una fila de las tablas");
        limpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarTablaActionPerformed(evt);
            }
        });

        funcionobjetivolabel2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        funcionobjetivolabel2.setForeground(new java.awt.Color(102, 102, 102));
        funcionobjetivolabel2.setText("(ms)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tiempoejecucionlabel1)
                            .addComponent(funcionobjetivolabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resultado)
                            .addComponent(resultiempoejecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(funcionobjetivolabel2)
                            .addComponent(funcionobjetivolabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(rutArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(examinarArchivo)
                                .addGap(110, 110, 110))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(Calcular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(limpiarTabla)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rutArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examinarArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Calcular)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3)
                                .addComponent(limpiarTabla)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcionobjetivolabel)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funcionobjetivolabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempoejecucionlabel1)
                    .addComponent(resultiempoejecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funcionobjetivolabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed

        String datosResultado[] = null;
        String resultadoModelo[] = null;
        Modelo modelo = new Modelo(numeroCajas, volumenesCajas, pesosCajas, volumenMorral, pesoMorral);
        double valorFO = 0;
        int tamanoArregloResultado = 0;

        double inicioTiempo = System.currentTimeMillis();
        try {
            resultadoModelo = modelo.modelar();

        } catch (LpSolveException ex) {
            Logger.getLogger(Morral.class.getName()).log(Level.SEVERE, null, ex);
        }
        double tiempoTotal = System.currentTimeMillis() - inicioTiempo;
        resultiempoejecucion.setText(Double.toString(tiempoTotal / 1000));

        if (resultadoModelo != null) {
            //Agregar a tabla resultados los morrales con sus cajas
            tamanoArregloResultado = Integer.parseInt(resultadoModelo[0]);
            valorFO = Double.parseDouble(resultadoModelo[1]);
            this.morrales = new int[tamanoArregloResultado];
            this.cajasEnMorrales = new String[tamanoArregloResultado];
            datosResultado = new String[2];

            int nummorral = 0;
            for (int j = 2; j < tamanoArregloResultado; j++) {
                this.morrales[nummorral] = nummorral + 1;
                datosResultado[0] = Integer.toString(this.morrales[nummorral]);
                this.cajasEnMorrales[j] = resultadoModelo[j];
                if (!"".equals(cajasEnMorrales[j])) {
                    datosResultado[1] = this.cajasEnMorrales[j];
                    modelResultado.addRow(datosResultado);
                }

                nummorral++;

            }

            //Mostrar resultado de f.o
            resultado.setText(resultadoModelo[1]);
        }

    }//GEN-LAST:event_CalcularActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void examinarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examinarArchivoActionPerformed

        Double datosMorral[] = null;
        Double datosCaja[] = null;
        resultado.setText("");

        JFileChooser dialogo = new JFileChooser();
        int opcion = dialogo.showOpenDialog(this);

        if (opcion == JFileChooser.APPROVE_OPTION) {

            tablaCaja.removeAll();
            String ruta = dialogo.getSelectedFile().getPath();
            rutArchivo.setText(ruta);
            File archivo = dialogo.getSelectedFile();
            FileReader filer = null;
            BufferedReader buffer = null;

            try {
                filer = new FileReader(archivo);
                buffer = new BufferedReader(filer);

                //Leer y agregar datos  a la tabla del morral        
                datosMorral = new Double[3];
                datosCaja = new Double[3];

                this.numeroCajas = Integer.parseInt(buffer.readLine());
                datosMorral[0] = (double) this.numeroCajas;
                this.pesoMorral = Double.parseDouble(buffer.readLine());
                datosMorral[1] = this.pesoMorral;
                this.volumenMorral = Double.parseDouble(buffer.readLine());
                datosMorral[2] = this.volumenMorral;
                modelMorral.addRow(datosMorral);

                //Leer y agregar datos a la tabla de las cajas
                this.numerosCaja = new int[this.numeroCajas];
                this.pesosCajas = new double[(int) this.numeroCajas];
                this.volumenesCajas = new double[(int) this.numeroCajas];
                //System.out.println("Numero Cajas " + numeroCajas);
                for (int i = 0; i < (int) this.numeroCajas; i++) {

                    String datos = buffer.readLine();
                    String[] arregloDatos = datos.split(" ");

                    this.numerosCaja[i] = Integer.parseInt(arregloDatos[0]);
                    //System.out.println("Caja " + this.numerosCaja[i]);
                    datosCaja[0] = (double) this.numerosCaja[i];

                    this.pesosCajas[i] = Double.parseDouble(arregloDatos[1]);
                    //System.out.print("Peso caja " + this.pesosCajas[i] + " ");
                    datosCaja[1] = this.pesosCajas[i];

                    this.volumenesCajas[i] = Integer.parseInt(arregloDatos[2]);
                    //System.out.println("Volumen caja " + this.volumenesCajas[i] + " ");
                    datosCaja[2] = this.volumenesCajas[i];

                    modelCaja.addRow(datosCaja);

                }

            } catch (Exception e) {
                System.out.println(e.toString());
            }

        }

    }//GEN-LAST:event_examinarArchivoActionPerformed


    private void limpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarTablaActionPerformed

        for (int x = 0; x < tablaMorral.getRowCount(); x++) {
            this.modelMorral.removeRow(x);

        }

        for (int x = 0; x < tablaCaja.getRowCount(); x++) {
            this.modelCaja.removeRow(x);

        }

        for (int x = 0; x < tablaResultado.getRowCount(); x++) {
            this.modelResultado.removeRow(x);

        }
        resultado.setText("");
        resultiempoejecucion.setText("");
    }//GEN-LAST:event_limpiarTablaActionPerformed

    public static void main(String args[]) {

        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Morral.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Morral.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Morral.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Morral.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Morral().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JButton examinarArchivo;
    private javax.swing.JLabel funcionobjetivolabel;
    private javax.swing.JLabel funcionobjetivolabel1;
    private javax.swing.JLabel funcionobjetivolabel2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limpiarTabla;
    private javax.swing.JTextField resultado;
    private javax.swing.JTextField resultiempoejecucion;
    private javax.swing.JTextField rutArchivo;
    private javax.swing.JTable tablaCaja;
    private javax.swing.JTable tablaMorral;
    private javax.swing.JTable tablaResultado;
    private javax.swing.JLabel tiempoejecucionlabel1;
    // End of variables declaration//GEN-END:variables

}
